"""add_prompt_version_to_suite

Revision ID: 19bc9e3e0985
Revises: 4e8c43dfca9a
Create Date: 2026-05-21 13:53:21.988142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19bc9e3e0985'
down_revision: Union[str, Sequence[str], None] = '4e8c43dfca9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('benchmark_suites', 'semantic_similarity_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0.7'::double precision"))
    op.alter_column('benchmark_suites', 'keyword_coverage_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0.6'::double precision"))
    op.alter_column('benchmark_suites', 'json_validity_required',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('benchmark_suites', 'json_validity_required',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('benchmark_suites', 'keyword_coverage_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0.6'::double precision"))
    op.alter_column('benchmark_suites', 'semantic_similarity_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0.7'::double precision"))
    # ### end Alembic commands ###
