"""add_prompt_version_to_suite

Revision ID: bbd554023a9d
Revises: 3b1e9d6a4f20
Create Date: 2026-05-20 20:58:50.406769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd554023a9d'
down_revision: Union[str, Sequence[str], None] = '3b1e9d6a4f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
