"""add_token_usage_estimated

Revision ID: d34da7d08a1b
Revises: 5daf10ca3dac
Create Date: 2026-05-21 14:42:45.187671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd34da7d08a1b'
down_revision: Union[str, Sequence[str], None] = '5daf10ca3dac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('token_usage_estimated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluations', 'token_usage_estimated')
    # ### end Alembic commands ###
