"""add_token_usage_estimated

Revision ID: d5f60a1ca6d6
Revises: d34da7d08a1b
Create Date: 2026-05-21 14:50:51.772243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5f60a1ca6d6'
down_revision: Union[str, Sequence[str], None] = 'd34da7d08a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
