FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --upgrade pip && \
    pip install --no-cache-dir --timeout 300 -r requirements.txt

COPY . .

CMD ["python", "-m", "dramatiq", "app.workers.benchmark_worker", "app.workers.evaluation_worker", "--processes", "2", "--threads", "4"]
